### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by haobinnan** [rhboot/grub2#23]
https://codeload.github.com/rhboot/grub2/tar.gz/fedora-29

./configure --with-platform=pc --target=i386

There is no reboot module and linuxefi module after compilation.
Does https://codeload.github.com/rhboot/grub2/tar.gz/fedora-29 have included a security boot patch by default?

**Comment by haobinnan** [comment]
insmod part_gpt
insmod part_msdos
insmod png
insmod all_video
insmod gfxterm

loadfont $prefix/font.pf2

set timeout=0
set default=0
set gfxpayload=1024x768

menuentry 'system' {
    echo 'Loading ...'
    if cpuid -l; then
        linux /bzImage loglevel=3
    else
        linux /bzImage_x86 loglevel=3
    fi
    initrd /initramfs
}

(./configure --with-platform=pc --target=i386) The traditional bios mode starts "set gfxpayload=1024x768" without execution, https://codeload.github.com/rhboot/grub2/tar.gz/fedora- 28 is ok.

**Comment by haobinnan** [comment]
./configure --with-platform=efi --target=i386
Unable to start windows (32bit uefi) via chainloader
chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi

**Comment by vathpela** [comment]
Should be fixed in the current tree.
