### ISSUE TITLE
fedora-30: Skipping grub.d/01_menu_auto_hide on serial terminals is unsafe when also using 01_fallback_counting

### ISSUE THREAD

**Issue by LorbusChris** [rhboot/grub2#48]
...due to the fallback snippet's reliance on the line `set boot_success=0` from the menu hide script.

I therefore propose to split out resetting boot_success into its own script snippet.

This could look like this: https://gist.github.com/LorbusChris/dafd9bc3e0a30a32835eb49740b0fe27

Also, could we split out both the menu hide and the fallback counting scripts into rpm subpackages?
Right now in FCOS, we delete them manually during the rpm-ostree compose: https://github.com/coreos/fedora-coreos-config/blob/master/fedora-coreos-base.yaml#L62

Will follow up with a proper PR once I got some feedback here.

cc @martinezjavier

**Comment by LorbusChris** [comment]
cc @jwrdegoede

**Comment by jwrdegoede** [comment]
The suggested split looks fine to me.
